.headers on
.mode box
SELECT 'chat_by_day_role' section, date(created_at) day, role, language, count(*) n, round(avg(length(content)),1) avg_len FROM chat_history WHERE created_at >= datetime('now','-14 days') GROUP BY day, role, language ORDER BY day DESC, role;
SELECT 'sessions' section, date(created_at) day, count(distinct session_id) sessions, min(created_at) first_at, max(created_at) last_at FROM chat_history WHERE created_at >= datetime('now','-14 days') GROUP BY day ORDER BY day DESC;
SELECT 'annotations' section, date(created_at) day, language, count(*) n, round(avg(naturalness),2) avg_naturalness, round(avg(tunit_length),2) avg_tunit, round(avg(lexical_rarity),2) avg_lex_rarity, sum(self_correction) self_corr, group_concat(distinct comprehension) comprehension_values FROM turn_annotations WHERE created_at >= datetime('now','-14 days') GROUP BY day, language ORDER BY day DESC;
SELECT 'learning_created' section, date(created_at) day, language, status, count(*) n FROM learning_items WHERE created_at >= datetime('now','-14 days') GROUP BY day, language, status ORDER BY day DESC;
SELECT 'learning_status' section, language, status, count(*) n, sum(case when evidence_count=0 then 1 else 0 end) no_evidence, sum(case when last_seen_at is null then 1 else 0 end) never_seen, sum(case when last_produced_at is not null then 1 else 0 end) produced FROM learning_items GROUP BY language, status ORDER BY language,status;
SELECT 'evidence' section, date(created_at) day, language, skill, event, count(*) n, round(avg(confidence),2) avg_conf FROM learning_item_evidence WHERE created_at >= datetime('now','-14 days') GROUP BY day, language, skill, event ORDER BY day DESC, language, skill, event;
SELECT 'practice' section, date(created_at) day, language, status, count(*) n, sum(case when completed_at is not null then 1 else 0 end) completed, round(avg(grade),2) avg_grade FROM learning_practice_attempts WHERE created_at >= datetime('now','-14 days') GROUP BY day, language, status ORDER BY day DESC;
SELECT 'errors' section, date(created_at) day, language, category, count(*) n FROM error_log WHERE created_at >= datetime('now','-14 days') GROUP BY day, language, category ORDER BY day DESC, n DESC;
SELECT 'proficiency' section, date(created_at) day, language, skill, dimension, challenge_band, outcome, count(*) n FROM proficiency_evidence WHERE created_at >= datetime('now','-14 days') GROUP BY day, language, skill, dimension, challenge_band, outcome ORDER BY day DESC;
